### ISSUE TITLE
Plugin style seems broken in latest on jenkins LTS

### ISSUE THREAD

**Issue by salavessa** [jan-molak/jenkins-build-monitor-plugin#518]
The current plugin release lifecycle to jenkins looks odd - there are currently 12 `1.13` releases, 9 of which were released in the last 4 days.

Public releases of the plugin have been observed at https://updates.jenkins-ci.org/download/plugins/build-monitor-plugin/ and https://plugins.jenkins.io/build-monitor-plugin/#releases

The latest `1.13` release builds also seems to have styling issues (at least when used with [jenkins LTS](https://www.jenkins.io/changelog-stable/)).
The plugin seems to be pushed to the jenkins update repo too often (and maybe some extra testing would be required)?

Thanks

**Comment by basil** [comment]
This caused by the custom hosting and release process developed by @jan-molak. The standard hosting and released process used by the @jenkinsci organization ([JEP-229](https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc)) has a way of using labels to mark certain PRs (e.g. dependency updates) as ineligible for release. I have offered to migrate this repository to the @jenkinsci organization and set up JEP-229, but the decision is up to @jan-molak.

**Comment by salavessa** [comment]
Thanks @basil.
@jan-molak, is @basil's help and approach something you could please consider adopting?
I have no concrete numbers but I guess this is/will affect many jenins around the world.
Thanks!

**Comment by jan-molak** [comment]
Hi @salavessa!

> The current plugin release lifecycle to jenkins looks odd

Build Monitor uses a continuous deployment workflow, where every change that's merged to master and passes the automated tests is automatically released to the Jenkins registry.

My thinking behind it was that if anything was good to go to master, it should be made available to the community, no matter if it's a dependency update or a code change. Especially that not keeping up to date with dependencies can be a cause of security issues...

Note that I've developed this system back in 2013, so about 6 years before the Jenkins project had this capability. While I still believe this is the right approach, I probably would've gone about the versioning scheme a bit differently if I was to design it again.

> there are currently 12 1.13 releases, 9 of which were released in the last 4 days.

That's correct, recently Build Monitor Contributors have been doing an amazing job helping to revive Build Monitor, and I've been doing my best to get the PRs merged to help keep the momentum going. And again, as soon as a PR is merged - it gets released.

> The plugin seems to be pushed to the jenkins update repo too often

I'm not sure about that. If there are new fixes available, wouldn't we want to make them available as soon as they can be used?

@basil, @dcendents - is there any reason why the current continuous deployment approach should be revised?

> The latest 1.13 release builds also seems to have styling issues (at least when used with jenkins LTS).

Interesting, thanks for reporting that! Would you be able to tell us more about the behaviour you see vs what you'd expect? Could you attach any screenshots to help us see what you see? Are there any errors visible in the browser log?

Let's try to get to the bottom of it!

**Comment by basil** [comment]
> @basil, @dcendents - is there any technical reason why the current continuous deployment approach should be revised?

Well, code cleanup PRs and dependency updates are generally useful to merge, but spinning a dedicated release for them and forcing users to upgrade to that release when its changelog just consists of entries like "No user-visible changes" tends to annoy users. That's why JEP-229 ignores Dependabot PRs and code cleanup (based on label) and requires PRs to be labelled as e.g. "bug" or "RFE" for continuous deployment to kick in. This seems to have struck a chord with users.

> The latest 1.13 release builds also seems to have styling issues (at least when used with jenkins LTS).

There was indeed a recent regression, but it was fixed in #517.

**Comment by salavessa** [comment]
Hi @jan-molak and @basil,

Thanks for the info - I can confirm that the latest release/build `1.13+build.202111220004` has fixed the styling bug initially reported.

I still believe that having such short release cycles makes it odd specially if you notice a bug in a release you just installed and when you rollback to the previous one (or update to the new latest) and the bug is still there - I ended up pretty "lost" to find a good release/version to rollback to so in my case and to be safe, I just revertd to the one from 1st October (i.e. 8 releases before the latest available by then).

Anyway, good work and thanks for the quick fix on #517 

Thanks!
